android doesn't have libpthread
ERROR: /hack/freedom/tensorflow/tensorflow/tensorflow/BUILD:714:1: Linking of rule '//tensorflow:libtensorflow_framework.so' failed (Exit 1)
external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lpthread
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/tools/benchmark:benchmark_model failed to build
Use --verbose_failures to see the command lines of failed build steps.